(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['index'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!-- Page Heading -->\n<p></p>\n<div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\n  <h1 class=\"h3 mb-0 text-gray-800\"> Snapshot of Balr Twitter @ "
    + alias4(((helper = (helper = lookupProperty(helpers,"date") || (depth0 != null ? lookupProperty(depth0,"date") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"date","hash":{},"data":data,"loc":{"start":{"line":4,"column":64},"end":{"line":4,"column":72}}}) : helper)))
    + "</h1>\n\n</div>\n\n<!-- Content Row -->\n<div class=\"row\">\n\n\n  <!-- Earnings (Monthly) Card Example -->\n  <div class=\"col-xl-3 col-md-6 mb-4\">\n    <div class=\"card border-left-primary shadow h-100 py-2\">\n      <div class=\"card-body\">\n        <div class=\"row no-gutters align-items-center\">\n          <div class=\"col mr-2\">\n            <div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">Followers (Total)</div>\n            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"followers") || (depth0 != null ? lookupProperty(depth0,"followers") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"followers","hash":{},"data":data,"loc":{"start":{"line":19,"column":64},"end":{"line":19,"column":77}}}) : helper)))
    + "</div>\n          </div>\n          <div class=\"col-auto\">\n            <i class=\"fas fa-calendar fa-2x text-gray-300\"></i>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  <!-- Earnings (Monthly) Card Example -->\n  <div class=\"col-xl-3 col-md-6 mb-4\">\n    <div class=\"card border-left-success shadow h-100 py-2\">\n      <div class=\"card-body\">\n        <div class=\"row no-gutters align-items-center\">\n          <div class=\"col mr-2\">\n            <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">Tweets (12M)</div>\n            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"statuses") || (depth0 != null ? lookupProperty(depth0,"statuses") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"statuses","hash":{},"data":data,"loc":{"start":{"line":36,"column":64},"end":{"line":36,"column":76}}}) : helper)))
    + " </div>\n          </div>\n          <div class=\"col-auto\">\n            <i class=\"fas fa-dollar-sign fa-2x text-gray-300\"></i>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  <!-- Earnings (Monthly) Card Example -->\n  <div class=\"col-xl-3 col-md-6 mb-4\">\n    <div class=\"card border-left-info shadow h-100 py-2\">\n      <div class=\"card-body\">\n        <div class=\"row no-gutters align-items-center\">\n          <div class=\"col mr-2\">\n            <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">Total retweets (12M)</div>\n            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"retweet_count") || (depth0 != null ? lookupProperty(depth0,"retweet_count") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"retweet_count","hash":{},"data":data,"loc":{"start":{"line":53,"column":64},"end":{"line":53,"column":81}}}) : helper)))
    + " </div>\n          </div>\n          <div class=\"col-auto\">\n            <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  <!-- Pending Requests Card Example -->\n  <div class=\"col-xl-3 col-md-6 mb-4\">\n    <div class=\"card border-left-warning shadow h-100 py-2\">\n      <div class=\"card-body\">\n        <div class=\"row no-gutters align-items-center\">\n          <div class=\"col mr-2\">\n            <div class=\"text-xs font-weight-bold text-warning text-uppercase mb-1\">Total favourites (12M)</div>\n            <div class=\"h5 mb-0 font-weight-bold text-gray-800\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"favourite_count") || (depth0 != null ? lookupProperty(depth0,"favourite_count") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"favourite_count","hash":{},"data":data,"loc":{"start":{"line":70,"column":64},"end":{"line":70,"column":83}}}) : helper)))
    + "</div>\n          </div>\n          <div class=\"col-auto\">\n            <i class=\"fas fa-comments fa-2x text-gray-300\"></i>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n\n<!-- Content Row -->\n\n<div class=\"row\">\n\n  <!-- Area Chart -->\n  <div class=\"col-xl-8 col-lg-7\">\n    <div class=\"card shadow mb-4\">\n      <!-- Card Header - Dropdown -->\n      <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n        <h6 id='charttitle' class=\"m-0 font-weight-bold text-primary\">Favourites by month</h6>\n        <div class=\"dropdown no-arrow\">\n          <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\"\n            aria-haspopup=\"true\" aria-expanded=\"false\">\n            <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\n          </a>\n          <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\" aria-labelledby=\"dropdownMenuLink\">\n            <div class=\"dropdown-header\">Tweet engagement:</div>\n            <a class=\"dropdown-item\" href=\"javascript:updateDashboardFavourites(dbData);\">Favourited</a>\n            <a class=\"dropdown-item\" href=\"javascript:updateDashboardRetweets(dbData);\">Retweeted</a>\n          </div>\n        </div>\n      </div>\n      <!-- Card Body -->\n      <div class=\"card-body\" style='margin-top: 10px'>\n        <div class=\"chart-area\">\n          <canvas id=\"myAreaChart\"></canvas>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  <!-- Pie Chart -->\n  <div class=\"col-xl-4 col-lg-5\">\n    <div class=\"card shadow mb-4\">\n      <!-- Card Header - Dropdown -->\n      <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n        <h6 id='mostboxname' class=\"m-0 font-weight-bold text-primary\">Most Favourited Tweet</h6>\n      </div>\n      <!-- Card Body -->\n      <div id='embededtweet2' class=\"card-body\">\n        <div class=\"chart-area\">\n          <blockquote class=\"twitter-tweet\" data-cards=\"hidden\" data-conversation=\"none\">\n            <a id='mosttweetbox' href=\"https://twitter.com/balr/status/"
    + alias4(((helper = (helper = lookupProperty(helpers,"most_favourited_id") || (depth0 != null ? lookupProperty(depth0,"most_favourited_id") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"most_favourited_id","hash":{},"data":data,"loc":{"start":{"line":123,"column":71},"end":{"line":123,"column":93}}}) : helper)))
    + "?ref_src=twsrc%5Etfw\"></a>\n          </blockquote>\n          <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n\n<!-- Content Row -->\n\n<div class='row'>\n\n  <!-- Content Column -->\n  <div class=\"col-xl-4 col-lg-3\">\n\n    <!-- Project Card Example -->\n    <div class=\"card shadow mb-4\">\n      <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n        <h6 class=\"m-0 font-weight-bold text-primary\">Other hashtags seen with #Balr (7D)</h6>\n      </div>\n      <div class=\"card-body\"  style='margin-top: 10px'>\n        <div class=\"chart-area\">\n          <h4 class=\"small font-weight-bold\">#"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_1_hashtag") || (depth0 != null ? lookupProperty(depth0,"hashtag_1_hashtag") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_1_hashtag","hash":{},"data":data,"loc":{"start":{"line":146,"column":46},"end":{"line":146,"column":67}}}) : helper)))
    + " <span class=\"float-right\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_1_count") || (depth0 != null ? lookupProperty(depth0,"hashtag_1_count") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_1_count","hash":{},"data":data,"loc":{"start":{"line":146,"column":94},"end":{"line":146,"column":113}}}) : helper)))
    + "</span>\n          </h4>\n          <div class=\"progress mb-4\">\n            <div id=\"hashtag_1\" class=\"progress-bar bg-danger\" role=\"progressbar\"\n              style=\"width: "
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_1_percentage") || (depth0 != null ? lookupProperty(depth0,"hashtag_1_percentage") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_1_percentage","hash":{},"data":data,"loc":{"start":{"line":150,"column":28},"end":{"line":150,"column":52}}}) : helper)))
    + "\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n          </div>\n          <h4 class=\"small font-weight-bold\">#"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_2_hashtag") || (depth0 != null ? lookupProperty(depth0,"hashtag_2_hashtag") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_2_hashtag","hash":{},"data":data,"loc":{"start":{"line":152,"column":46},"end":{"line":152,"column":67}}}) : helper)))
    + "<span class=\"float-right\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_2_count") || (depth0 != null ? lookupProperty(depth0,"hashtag_2_count") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_2_count","hash":{},"data":data,"loc":{"start":{"line":152,"column":93},"end":{"line":152,"column":112}}}) : helper)))
    + "</span>\n          </h4>\n          <div class=\"progress mb-4\">\n            <div id=\"hashtag_2\" class=\"progress-bar bg-warning\" role=\"progressbar\"\n              style=\"width: "
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_2_percentage") || (depth0 != null ? lookupProperty(depth0,"hashtag_2_percentage") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_2_percentage","hash":{},"data":data,"loc":{"start":{"line":156,"column":28},"end":{"line":156,"column":52}}}) : helper)))
    + "\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n          </div>\n          <h4 class=\"small font-weight-bold\">#"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_3_hashtag") || (depth0 != null ? lookupProperty(depth0,"hashtag_3_hashtag") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_3_hashtag","hash":{},"data":data,"loc":{"start":{"line":158,"column":46},"end":{"line":158,"column":67}}}) : helper)))
    + "<span class=\"float-right\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_3_count") || (depth0 != null ? lookupProperty(depth0,"hashtag_3_count") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_3_count","hash":{},"data":data,"loc":{"start":{"line":158,"column":93},"end":{"line":158,"column":112}}}) : helper)))
    + "</span>\n          </h4>\n          <div class=\"progress mb-4\">\n            <div id=\"hashtag_3\" class=\"progress-bar\" role=\"progressbar\" style=\"width: "
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_3_percentage") || (depth0 != null ? lookupProperty(depth0,"hashtag_3_percentage") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_3_percentage","hash":{},"data":data,"loc":{"start":{"line":161,"column":86},"end":{"line":161,"column":110}}}) : helper)))
    + "\"\n              aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n          </div>\n          <h4 class=\"small font-weight-bold\">#"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_4_hashtag") || (depth0 != null ? lookupProperty(depth0,"hashtag_4_hashtag") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_4_hashtag","hash":{},"data":data,"loc":{"start":{"line":164,"column":46},"end":{"line":164,"column":67}}}) : helper)))
    + "<span class=\"float-right\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_4_count") || (depth0 != null ? lookupProperty(depth0,"hashtag_4_count") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_4_count","hash":{},"data":data,"loc":{"start":{"line":164,"column":93},"end":{"line":164,"column":112}}}) : helper)))
    + "</span>\n          </h4>\n          <div class=\"progress mb-4\">\n            <div id=\"hashtag_4\" class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: "
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_4_percentage") || (depth0 != null ? lookupProperty(depth0,"hashtag_4_percentage") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_4_percentage","hash":{},"data":data,"loc":{"start":{"line":167,"column":94},"end":{"line":167,"column":118}}}) : helper)))
    + "\"\n              aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n          </div>\n          <h4 class=\"small font-weight-bold\">#"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_5_hashtag") || (depth0 != null ? lookupProperty(depth0,"hashtag_5_hashtag") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_5_hashtag","hash":{},"data":data,"loc":{"start":{"line":170,"column":46},"end":{"line":170,"column":67}}}) : helper)))
    + "<span class=\"float-right\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_5_count") || (depth0 != null ? lookupProperty(depth0,"hashtag_5_count") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_5_count","hash":{},"data":data,"loc":{"start":{"line":170,"column":93},"end":{"line":170,"column":112}}}) : helper)))
    + "</span>\n          </h4>\n          <div class=\"progress\">\n            <div id=\"hashtag_5\" class=\"progress-bar bg-success\" role=\"progressbar\"\n              style=\"width: "
    + alias4(((helper = (helper = lookupProperty(helpers,"hashtag_5_percentage") || (depth0 != null ? lookupProperty(depth0,"hashtag_5_percentage") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hashtag_5_percentage","hash":{},"data":data,"loc":{"start":{"line":174,"column":28},"end":{"line":174,"column":52}}}) : helper)))
    + "\" aria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  <!-- Random tweet -->\n  <div class=\"col-xl-4 col-lg-3\">\n    <div class=\"card shadow mb-4\">\n      <!-- Card Header - Dropdown -->\n      <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n        <h6 class=\"m-0 font-weight-bold text-primary\">Random Tweet with #Balr</h6>\n      </div>\n      <div id='embededtweet1' class=\"card-body\">\n        <div class=\"chart-area\">\n          <blockquote class=\"twitter-tweet\" data-cards=\"hidden\" data-conversation=\"none\"> \n            <a href=\"https://twitter.com/"
    + alias4(((helper = (helper = lookupProperty(helpers,"random_user_name") || (depth0 != null ? lookupProperty(depth0,"random_user_name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"random_user_name","hash":{},"data":data,"loc":{"start":{"line":191,"column":41},"end":{"line":191,"column":61}}}) : helper)))
    + "/status/"
    + alias4(((helper = (helper = lookupProperty(helpers,"random_tweet_id") || (depth0 != null ? lookupProperty(depth0,"random_tweet_id") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"random_tweet_id","hash":{},"data":data,"loc":{"start":{"line":191,"column":69},"end":{"line":191,"column":88}}}) : helper)))
    + "?ref_src=twsrc%5Etfw\"></a>\n          </blockquote>\n          <script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>\n        <p><b>User name:</b> "
    + alias4(((helper = (helper = lookupProperty(helpers,"random_user_name") || (depth0 != null ? lookupProperty(depth0,"random_user_name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"random_user_name","hash":{},"data":data,"loc":{"start":{"line":194,"column":29},"end":{"line":194,"column":49}}}) : helper)))
    + "</p>\n        <p><b>Total followers:</b> "
    + alias4(((helper = (helper = lookupProperty(helpers,"random_tweet_followers") || (depth0 != null ? lookupProperty(depth0,"random_tweet_followers") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"random_tweet_followers","hash":{},"data":data,"loc":{"start":{"line":195,"column":35},"end":{"line":195,"column":61}}}) : helper)))
    + "</p>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  <!-- Illustrations -->\n  <div class=\"col-xl-4 col-lg-3\">\n    <div class=\"card shadow mb-4\">\n      <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n        <h6 class=\"m-0 font-weight-bold text-primary\">Languages for Tweets containing #Balr (7D)</h6>\n      </div>\n      <!-- Card Body -->\n      <div class=\"card-body\" style='margin-top: 10px'>\n        <div class=\"chart-area\">\n          <canvas id=\"myPieChart\"></canvas>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  </div>\n  <div class=\"row\">\n    <div class=\"col-xl-12 col-lg-3\">\n      <div class=\"card shadow mb-4\">\n        <!-- Card Header - Dropdown -->\n        <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n          <h6 class=\"m-0 font-weight-bold text-primary\">Data Caveats</h6>\n        </div>\n        <div class=\"card-body\">\n          <p>-All data for the user 'Balr' is 12 month's, this includes retweets/favourites by month and most\n            favourited tweet</p>\n          <p>-Tweets using #Balr, including other Hashtags, Random tweet and Languages with #Balr is a 7 day period, due\n            to quantity of tweets and limitation of request with Twitter API. Total tweets last 7 days = "
    + alias4(((helper = (helper = lookupProperty(helpers,"total_tweets") || (depth0 != null ? lookupProperty(depth0,"total_tweets") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"total_tweets","hash":{},"data":data,"loc":{"start":{"line":228,"column":105},"end":{"line":228,"column":121}}}) : helper)))
    + "\n            tweets</p>\n          <p>-Tweet language used as proxy for location, twitter does not have reliable location data on users (Location field is user generated)</p>\n          <p>-This dashboard was developed to view on a computer, not the most mobile friendly page.</p>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>";
},"useData":true});
})();